### ISSUE TITLE
Interactive Graphs

### ISSUE THREAD

**Issue by yasmin2496** [buildly-release-management/buildly-react-template#13]
- [ ] Timeline for Requirements to Issues
- [ ] Timeline from created to assigned 
- [ ] Timeline from assigned to completed
- [ ] Requirements / Issues category wise
- [ ] Milestones

![image](https://user-images.githubusercontent.com/60848892/152783367-68372edc-32c0-499d-8091-5263659e1f13.png)
Description: Showing the number of tickets graph which shows no. of features and no. of issues present in the project that the user select

**Comment by RadhikaPPatel** [comment]
PR is put on hold
