### ISSUE TITLE
Registration screen shows archived products from Stripe

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#161]
Stripe has several products related to the consulting side that are archived but can not be deleted because they have been used.  We need to filter out the archived products from the drop down.

**Comment by glind** [comment]
![Image](https://user-images.githubusercontent.com/449810/185204544-ec71190f-3e5e-46f9-bf02-64b47466f0ab.png)

**Comment by RadhikaPPatel** [comment]
Removed stripe setup for now. So this is no more an option.
