### ISSUE TITLE
Top 5 Priority Features should be created as Features

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#167]
![Image](https://user-images.githubusercontent.com/449810/186702947-2fbd1dde-2a26-4f8f-a581-aa85bf3760db.png)

WE should ask for the Products "Top 5 Priority or biggest features" and created them as "features" that are then synced to the Trello Board or allow them to pull them in from Trello if they have them already.  These should then be the defining Features for the estimation process.

**Comment by RadhikaPPatel** [comment]
This last page was removed from product form. So no longer relevant.
