### ISSUE TITLE
Fixes from dev release 09/29

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#172]
**Product Creation Wizard.**  

- [x] Remove the "buildly architecture questions"
- [x] Remove the question Is there a specific problem you are trying to solve If Yes, for what type of user? Yes No
- [x] Instead ask question about business segment first "What is your primary business segment?" dropdown... Then who are  users... dropdown...secondary...dropdown.

- [x] The features screen the very last screen.. should be replaced with the add a new feature popup from the dashboard.  Then allow them to add 5 features and no more (to add more then 5 upgrade)

- [x] The Binary upload of documents does not seem to be there, I know that Mounika had worked on that and had it almost done if not done.  There might be an open pull request or branch that needs to be merged.

**Dashboard and Navigation.**

- [x] We need the link to the release section working, is should be in the navigation dropdown under products

**New Feature**
- [x] Remove the fields  Status, Priority  and Tags from the create form.
- [x] You can't edit the logic of a feature once it has been saved, you should be able to do that.

**Comment by glind** [comment]
Please get what you can off this done and pushed out to dev tomorrow and Jeffrey and I will review again.

**Comment by RadhikaPPatel** [comment]
@glind All these feature require FE as well as BE changes. So it will take little time as I am alone doing these changes. I have already started working on these though.
