### ISSUE TITLE
Feedback from dev 10/20

### ISSUE THREAD

**Issue by RadhikaPPatel** [buildly-release-management/buildly-react-template#182]
#### **Error displaying**

* Registration and Email work great…
- [x] Feedback on username already in use as opposed to "problem with registration" would be nice. Where are these types of errors being logged?

#### **New Product Screen after registration**

- [x]  Help text for first time "Thanks for registering, to get you started we want to take your through a new product wizard, this will help you get oriented with the system, and create your first product with. Inisights!… let's get started…"
- [x] Start Date is great.. End date should be 2 months out by default ( I don't think we need a timestamp)
* We will design some content for how to get your access token for each tool that can pop-up and guide you
- [x] Primary Business Segment is a multiple select so we should probably relabel it "What our your primary business segments?"
- [x] Who are your users should be a label for the user to create then a user type (the current dropdown) and allow for primary and secondary and tertiary for now.

#### **Miscellaneous**

- [x] Do you already have requirements in your connected project planning tool?  should be a yes/no boolean field not a text field
- [x] How Many Users do expect to accommodate per Month not per day in title
- [x] Let's say Use my Own team rather then just "own" and if I select own I should be able to move on and I can't so let's default to "hire"
* Timezone I assume is data driven? Do we need a source for timezone?  I can't get past the screen without values in that required drop down
- [x] Can not cancel out of screen or close without finishing and I can't finish

#### **New brand colors**

- [x] New color scheme
* Blue: #0C5595
* Background: #DCDCE0
* Text: #000
* Orange: #F9943B
* Dark Blue: #162944 (Header in Insights background color should be this)
* Contrast Background: #121212
* Contrast Text: #ffffff

**Comment by RadhikaPPatel** [comment]
@glind Registration error are logged in the console of User browser

**Comment by glind** [comment]
> 

Yes but i'm not sure that will. help most users.  They don't see that, I think we could give them a "please try a different username" at least for that particular error.  This also comes back to that username or email problem we have had with Django forever.

**Comment by RadhikaPPatel** [comment]
@glind Can you please share the mockup for user type that we discussed on Monday meeting?

**Comment by RadhikaPPatel** [comment]
@glind Reminder for the mockup

**Comment by glind** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/449810/200002103-89e85c19-e90f-44a0-97c5-67b5f2f52d99.png)
This allows for multiple users (a label) that are defined by user type.
