### ISSUE TITLE
Punch list Dec 7

### ISSUE THREAD

**Issue by RadhikaPPatel** [buildly-release-management/buildly-react-template#195]
- [x] Description in the list view should be limited to 200 chars or too with a "…" to hover over and see the full disruption. 

- [x] Can't edit an Issue without selecting a repository, but dropdown does not stick on repository selection so save button stays disabled.

- [x] Status is from Trello…where should this come from for an issue?  It should probably just had a status of "open", "assigned", "waiting for feedback" or "complete".

- [x] Kanban view: card with comments should be green with a number count next to it for the number of comments.  Same for Tabular view, though I think the comments should be move out of the Actions section into just the same green or black icon with the count.

- [x] After save an edited feature or just closing the edit pop-up, the filter selected in the features section disappears

- [x] Configuration board still displays on occasion when loading a product even well after the board has been configured, still need a way to edit a configuration in a product admin section.

- [x] New Product section still requires a Role be entered with greater then 0 before next button works

- [x] No suggested Features for new product with B2B and Mobile and Desktop with a complexity score of 15 and cost 2.

- [x] Can we import and export images that are attached to a card or feature in trello or github?

**Comment by glind** [comment]
How did we do on this? @odenypeter @IvyMMutiso @RadhikaPPatel ?  I think most of these are still open?

**Comment by glind** [comment]
Open check boxes have been converted to issues
