### ISSUE TITLE
We need a front end AI assistant integration link and icon that is aware of the User, Product and URL from each request and contextualize responses sent to the Backend.

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#233]
Basic functionality for v0.5 of this.

- [ ] Connect to ChatGPT with context on users current Product and Features through backend service https://github.com/buildlyio/ai-onboarding

- [ ] Front End Chat Module that sends a question to the backend and then display the response.  Should open up with a link to a random article from the Insights Help blog and a way to search for other help documents there as well. https://www.buildly.io/news/category/insightshelp/

- [ ] Users should be provided with a quick question button "Suggest a Feature for my Product" that should send the question to the backend along with the product ID, backend should then send the context of the Product and existing features to ChatGPT and suggest a feature in the send the link to that feature as a suggested feature.  (Premium Feature)

**Comment by patelradhika** [comment]
@glind I saw some discussion around LangChain, OpenAI and SQL for suggestions on data stored in our Databases. So I am exploring this more. I also need to figure out how to test this and deploy this if we go with this approach.
