### ISSUE TITLE
Can not add the first ticket to a swimlane via Kanban view.

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#246]
![Image](https://github.com/buildly-release-management/buildly-react-template/assets/449810/a3ab281b-3c5d-42fb-8c94-86511ce42bd8)

![Image](https://github.com/buildly-release-management/buildly-react-template/assets/449810/a5ce48a2-296b-40bc-80ff-8b3980545324)

**Comment by TanmayJain92** [comment]
@odenypeter While updating an issue, assignees should not be a required field as per my understanding.

![Image](https://github.com/buildly-release-management/buildly-react-template/assets/152588390/794f6b22-2e30-43be-a181-13c940153676)

**Comment by TanmayJain92** [comment]
@odenypeter Please ignore the above comment. The error was due to incorrect data sent to the API as we're sending "assignees" as "null" instead of empty array.
