### ISSUE TITLE
Can not update issues

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#263]
When editing issue fails.  Error message from console: bundle.js?bc0b3308bcfbcefb91ed:102 
        
        
       PUT https://insights-api.buildly.io/release/issue/6e3b7426-8958-41ce-abd8-62c7a3b75eb0/ 400 (Bad Request)400 Bad Request

**Comment by odenypeter** [comment]
@glind is this issue still there?
I pushed a temporary fix to dev
