### ISSUE TITLE
Add User Story Profile for each User in Product Wizard

### ISSUE THREAD

**Issue by patelradhika** [buildly-release-management/buildly-react-template#316]
Each Product wizard product have a list of users (admin,poweruser, user etc.)  For each user we need a way to generate a profile either through AI or having the user create is based on there customer profile.  We need a UI to add and edit those and backend model to store them.

**Comment by glind** [comment]
![Screenshot 2024-07-22 at 8 20 25 AM](https://github.com/user-attachments/assets/854b5010-fc13-45b3-b213-a8673748e0b6)
Add user Profile field (long description) for each new user added to a product
