### ISSUE TITLE
Kanban board does not have the same filters as the tabular view

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#331]
DESCRIPTION: The tabular view has nice search and filter functionality but there is nothing like that for the Kanban view. 
 ERROR MESSAGE: None 
 EXPECTED BEHAVIOUR:  
 STEPS TO REPRODUCE:  
 SEVERITY: Medium 
 APP NAME: Buildly Labs 
 VERSION: v0.8.0 
 COLLAB BUG URL https://labs.buildly.io/app/product-roadmap/kanban  
 IS USER SUBMITTED: True 
 IS APPROVED: True

**Comment by patelradhika** [comment]
Duplicate issue. #327
