### ISSUE TITLE
Swim lane ordering is not working or available

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#350]
DESCRIPTION: Swim lanes have a default order and nothing else, users can't organize swimlanes. 
 ERROR MESSAGE: No error message 
 EXPECTED BEHAVIOUR:  
 STEPS TO REPRODUCE:  
 SEVERITY: High 
 APP NAME: Buildly Labs 
 VERSION: v0.9.0 
 COLLAB BUG URL https://labs.buildly.io/app/product-roadmap/tool-status  
 IS USER SUBMITTED: True 
 IS APPROVED: True

**Comment by patelradhika** [comment]
Merged in PR #343 by @IvyMMutiso
