### ISSUE TITLE
No ability to edit release

### ISSUE THREAD

**Issue by glind** [buildly-release-management/buildly-react-template#351]
DESCRIPTION: the edit release function is not available from the release screen.  The new release function allows for bulk adding of features to a release we should be able to do the same from an edit screen. 
 ERROR MESSAGE: No error 
 EXPECTED BEHAVIOUR:  
 STEPS TO REPRODUCE:  
 SEVERITY: High 
 APP NAME: Buildly Labs 
 VERSION: v0.9.0 
 COLLAB BUG URL https://labs.buildly.io/app/release  
 IS USER SUBMITTED: True 
 IS APPROVED: True

**Comment by patelradhika** [comment]
Merged in PR #346
