### ISSUE TITLE
Create Developer User Registration and Login

### ISSUE THREAD

**Issue by yasmin2496** [buildly-release-management/buildly-react-template#45]

**Comment by glind** [comment]
Each user will register as a type of developer or product team member as well as have a unique organization name.  That organization will then interact with the platform differently depending on the type.

If that user is the first from their organization and the organization or user type is developer, then they must fill out the developer survey.  After that they should be redirected to the dashboard.

If that user is from the first from an organization that is of type product they must fill out the new product form.wizard.  After that they should be directed to the dashboard.

**Comment by yasmin2496** [comment]
@glind For the developers, do we show the Dashboard or just show a Work In Progress message.

Same goes for product team people, after product form filling up do we show them any message or redirect to Dashboard

**Comment by glind** [comment]
Yes, until it’s connected to the backend and working, let’s just have a message a top the dashboard that says coming soon.  If the BE is ready let’s save it there, but if not we can save it in excel sheet for now.
