### ISSUE TITLE
Create a common language requirements gathering wizard for Products.

### ISSUE THREAD

**Issue by yasmin2496** [buildly-release-management/buildly-react-template#64]
Diagram : https://app.diagrams.net/#G1isW5WBP4AFq9Fs1ypGtLyb2G2lzy_J_I
Flow Explanation Document: https://docs.google.com/document/d/1cePXTdDzRqIG_H3gNsdm0Wnwz8Cr1931/edit?usp=sharing&ouid=114192920582283856110&rtpof=true&sd=true

**Comment by glind** [comment]
This logic, from the diagram, should be used in as our first suggestion engine and ML component.
